//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Event.cpp
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#include "Event.h"

void Event::setDeviceName(int String) {
}

void Event::setDeviceID(int String) {
}

void Event::setPanPos(int int) {
}

void Event::setTiltPos(int int) {
}

void Event::setSpeed(int int) {
}

void Event::setTimestamp(int time) {
}

List Event::getEventData() {
}

void Event::deleteEvent() {
}

void Event::createEvent() {
}

