//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Event.cpp
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#include "Event.h"
#include <chrono>
#include <iomanip>
#include <sstream>
#include <ctime>

Event::Event(std::string name, std::string id, int pan, int tilt, int spd)
    : deviceName(name), deviceID(id), panPos(pan), tiltPos(tilt), speed(spd) {

    // 1. Get current system time
    auto now = std::chrono::system_clock::now();
    std::time_t now_c = std::chrono::system_clock::to_time_t(now);

    std::tm bt;
    // Thread-safe local time conversion
#ifdef _WIN32
    localtime_s(&bt, &now_c);
#else
    localtime_r(&now_c, &bt);
#endif

    // 2. Format the string: MM/DD/YYYY HH:MM:SS
    std::ostringstream oss;
    oss << std::setfill('0')
        << std::setw(2) << (bt.tm_mon + 1) << "/"
        << std::setw(2) << bt.tm_mday << "/"
        << (bt.tm_year + 1900) << " "
        << std::setw(2) << bt.tm_hour << ":"
        << std::setw(2) << bt.tm_min << ":"
        << std::setw(2) << bt.tm_sec;

    timestamp = oss.str();
}

std::string Event::getDeviceName() const { 
    return deviceName; 
}
std::string Event::getDeviceID()   const { 
    return deviceID; 
}
int Event::getPanPos()             const {
    return panPos; 
}
int Event::getTiltPos()            const { 
    return tiltPos; 
}
int Event::getSpeed()              const { 
    return speed; 
}
std::string Event::getTimestamp()  const { 
    return timestamp; 
}

