//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Event.h
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#ifndef EVENT_H
#define EVENT_H

#include <string>
#include <ctime>

class Event {
public:
    // Constructor handles timestamping automatically
    Event(std::string name, std::string id, int pan, int tilt, int spd);

    // Getters for CSV writing
    std::string getDeviceName() const;
    std::string getDeviceID()   const;
    int getPanPos()             const;
    int getTiltPos()            const;
    int getSpeed()              const;
    std::string getTimestamp()  const;

private:
    std::string deviceName;
    std::string deviceID;
    int panPos;
    int tiltPos;
    int speed;
    std::string timestamp;
};

#endif
