//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Event.h
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#if !defined(_EVENT_H)
#define _EVENT_H


class Event {
public:
	void setDeviceName(int String);
	void setDeviceID(int String);
	void setPanPos(int int);
	void setTiltPos(int int);
	void setSpeed(int int);
	void setTimestamp(int time);
	List getEventData();
	void deleteEvent();
	void createEvent();
private:
	String deviceName;
	String deviceID;
	int panPos;
	int tiltPos;
	int speed;
	Time timestamp;
};

#endif  //_EVENT_H
