//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Instruction.h
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#if !defined(_INSTRUCTION_H)
#define _INSTRUCTION_H


class Instruction {
public:
	void setPanPos(int int);
	void setTiltPos(int int);
	void setSpeed(int int);
	void setTimeDelay(int int);
	List readInstr();
	void createInstr();
	void deleteInstr();
private:
	int panPos;
	int tiltPos;
	int speed;
	int timeDelay;
};

#endif  //_INSTRUCTION_H
