//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Instruction.cpp
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#include "Instruction.h"

// Constructor implementation
Instruction::Instruction(int p, int t, int s, int d) {
    setPanPos(p);
    setTiltPos(t);
    setSpeed(s);
    setTimeDelay(d);
}

// Setters
void Instruction::setPanPos(int p) {
    panPos = std::clamp(p, PAN_MIN, PAN_MAX);
}

void Instruction::setTiltPos(int t) {
    tiltPos = std::clamp(t, TILT_MIN, TILT_MAX);
}

void Instruction::setSpeed(int s) {
    speed = std::clamp(s, SPEED_MIN, SPEED_MAX);
}

void Instruction::setTimeDelay(int d) {
    timeDelay = std::max(DELAY_MIN, d);
}

// Getters
int Instruction::getPan() const { 
    return panPos; 
}
int Instruction::getTilt() const { 
    return tiltPos; 
}
int Instruction::getSpeed() const { 
    return speed; 
}
int Instruction::getDelay() const {
    return timeDelay; 
}

