//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Instruction.cpp
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#include "Instruction.h"

void Instruction::setPanPos(int int) {
}

void Instruction::setTiltPos(int int) {
}

void Instruction::setSpeed(int int) {
}

void Instruction::setTimeDelay(int int) {
}

List Instruction::readInstr() {
}

void Instruction::createInstr() {
}

void Instruction::deleteInstr() {
}

