//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pan_Tilt Device.cpp
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#include "Pan_Tilt Device.h"

void Pan_Tilt Device::setPanPos(int int) {
}

int Pan_Tilt Device::getPanPos() {
}

void Pan_Tilt Device::setTiltPos(int int) {
}

int Pan_Tilt Device::getTiltPos() {
}

void Pan_Tilt Device::setSpeed(int int) {
}

int Pan_Tilt Device::getSpeed() {
}

String Pan_Tilt Device::getName() {
}

String Pan_Tilt Device::getID() {
}

List Pan_Tilt Device::getStatus() {
}

