//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pan_Tilt Device.h
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#if !defined(_PAN_TILT DEVICE_H)
#define _PAN_TILT DEVICE_H


class Pan_Tilt Device {
public:
	void setPanPos(int int);
	int getPanPos();
	void setTiltPos(int int);
	int getTiltPos();
	void setSpeed(int int);
	int getSpeed();
	String getName();
	String getID();
	List getStatus();
private:
	String deviceName;
	String deviceID;
	int panPos;
	int tiltPos;
	int speed;
};

#endif  //_PAN_TILT DEVICE_H
