//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PanTiltDevice.h
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#if !defined(PANTILTDEVICE_H)
#define PANTILTDEVICE_H

#include <string>
#include <vector>

class PanTiltDevice {
public:
	// Setters
    void setPanPos(int p);
    void setTiltPos(int t);
    void setSpeed(int s);

	// Getters
    int getPanPos() const;
    int getTiltPos() const;
    int getSpeed() const;

	std::string getName() const;
    std::string getID() const;

    std::vector<std::string> getStatus() const;

	// Constructor to define object in main
	PanTiltDevice(std::string n, std::string i, int pan = 0, int tilt = 0, int speed = 0);

private:
    int panPos;
    int tiltPos;
    int speed;
    std::string name;
    std::string id;
};

#endif  //PANTILTDEVICE_H
