//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PanTiltDevice.h
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#if !defined(PANTILTDEVICE_H)
#define PANTILTDEVICE_H

#include <string>
#include <vector>
#include "Instruction.h"

class PanTiltDevice {
public:
	// Setters
    void setPanPos(int p);
    void setTiltPos(int t);
    void setSpeed(int s);
    void setPlaying(bool status);
    void setLoadedProfile(std::string pName);

	// Getters
    int getPanPos() const;
    int getTiltPos() const;
    int getSpeed() const;
    bool isCurrentlyPlaying() const;
    std::string getLoadedProfile() const;

	std::string getName() const;
    std::string getID() const;

    std::vector<std::string> getStatus() const;

	// Constructor to define object in main
	PanTiltDevice(std::string n, std::string i, int pan = 0, int tilt = 0, int speed = 0);

    // Configuration
    void loadInstructions(std::string pName, const std::vector<Instruction>& instrs);
    Instruction getFirstInstruction() const;

private:
    int panPos;
    int tiltPos;
    int speed;
    std::string name;
    std::string id;
    bool isPlaying = false;
    std::string loadedProfileName = "None";
    std::vector<Instruction> activeInstructions;

    bool isMoving = false;
};

#endif  //PANTILTDEVICE_H
