//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pan_Tilt Device.cpp
//  @ Date : 3/25/2026
//  @ Author : 
//
//
#include "PanTiltDevice.h"   // make sure this matches your actual filename

// Constructor
PanTiltDevice::PanTiltDevice(std::string n, std::string i, int pan, int tilt, int spd)
    : name(n), id(i), panPos(pan), tiltPos(tilt), speed(spd) {}

// Setters
void PanTiltDevice::setPanPos(int p) {
    panPos = p;
}

void PanTiltDevice::setTiltPos(int t) {
    tiltPos = t;
}

void PanTiltDevice::setSpeed(int s) {
    speed = s;
}

// Getters
int PanTiltDevice::getPanPos() const {
    return panPos;
}

int PanTiltDevice::getTiltPos() const {
    return tiltPos;
}

int PanTiltDevice::getSpeed() const {
    return speed;
}

std::string PanTiltDevice::getName() const {
    return name;
}

std::string PanTiltDevice::getID() const {
    return id;
}

// Status function
std::vector<std::string> PanTiltDevice::getStatus() const {
    return {
        "Name: " + name,
        "ID: " + id,
        "Pan: " + std::to_string(panPos),
        "Tilt: " + std::to_string(tiltPos),
        "Speed: " + std::to_string(speed)
    };
}
