//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sweep_Profile.h
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#ifndef _SWEEP_PROFILE_H
#define _SWEEP_PROFILE_H

#include <string>
#include <vector>
#include "Instruction.h" // Assuming this defines your Instruction class

class Sweep_Profile {
public:
    // Constructor
    Sweep_Profile(std::string name) : profileName(name) {}

    // Getters and Setters
    void setName(std::string name) { profileName = name; }
    std::string getName() const { return profileName; }

    // Profile Configuration
    void addInstr(const Instruction& instr);
    bool saveProfile(); // Returns true if write to file succeeds
    static Sweep_Profile loadProfile(std::string filename);

    // Playback control
    void playProfile();
    void stopProfile();

private:
    std::string profileName;
    std::vector<Instruction> instrList; // The "List" from your diagram
};

#endif
