//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sweep_History.h
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#if !defined(_SWEEP_HISTORY_H)
#define _SWEEP_HISTORY_H


class Sweep_History {
public:
	void setName(int String);
	String getName();
	void addEvent(int List);
	List getEventList();
	void deleteHistory();
private:
	String logName;
	List eventList;
};

#endif  //_SWEEP_HISTORY_H
