//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sweep_Profile.h
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#if !defined(_SWEEP_PROFILE_H)
#define _SWEEP_PROFILE_H


class Sweep_Profile {
public:
	void setName(int String);
	String getName();
	void addInstr(int Instruction);
	void loadProfile(int List);
	void saveProfile(int bool);
	void playProfile(int List);
	void stopProfile(int List);
	void deleteProfile(int String);
private:
	String profileName;
	List instrList;
};

#endif  //_SWEEP_PROFILE_H
