//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sweep_Profile.h
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#ifndef _SWEEP_PROFILE_H
#define _SWEEP_PROFILE_H

#include <string>
#include <vector>
#include <thread>
#include <atomic>
#include "Instruction.h"
#include "PanTiltDevice.h"
#include <iostream>
#include <fstream>
#include <filesystem>

class Sweep_Profile {
public:
    // Constructor
    Sweep_Profile(std::string name);

    // Getters and Setters
    void setName(std::string name);
    std::string getName() const;

    // Profile Configuration
    void addInstr(const Instruction& instr);
    void saveProfile(bool save);
    std::vector<Instruction> loadProfile(std::string filename);
    void deleteProfile(std::string name);
    void clearInstrList() { instrList.clear(); }

    // Playback control
    void playProfile(std::vector<PanTiltDevice>& devices);
    void stopProfile(std::vector<PanTiltDevice>& devices);

private:
    std::string profileName;
    std::vector<Instruction> instrList;
    std::atomic<bool> isRunning{ false };
    void runBackground(std::vector<PanTiltDevice>* devices);
};

#endif
