//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sweep_Profile.cpp
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#include "Sweep_Profile.h"

void Sweep_Profile::setName(int String) {
}

String Sweep_Profile::getName() {
}

void Sweep_Profile::addInstr(int Instruction) {
}

void Sweep_Profile::loadProfile(int List) {
}

void Sweep_Profile::saveProfile(int bool) {
}

void Sweep_Profile::playProfile(int List) {
}

void Sweep_Profile::stopProfile(int List) {
}

void Sweep_Profile::deleteProfile(int String) {
}

