//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sweep_History.cpp
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#include "Sweep_History.h"
#include <filesystem>

namespace fs = std::filesystem;

Sweep_History::Sweep_History(std::string name) : logName(name) {
    if (!fs::exists("Logs")) {
        fs::create_directory("Logs");
    }

    std::string filePath = "Logs/" + logName + ".csv";

    // Check if it's a new file to write headers
    std::ifstream checkFile(filePath);
    bool isNew = !checkFile.good();
    checkFile.close();

    outFile.open(filePath, std::ios::app);

    if (isNew && outFile.is_open()) {
        outFile << "Timestamp,DeviceName,DeviceID,Pan,Tilt,Speed\n";
    }
}

Sweep_History::~Sweep_History() {
    if (outFile.is_open()) {
        outFile.close();
    }
}

void Sweep_History::addEvent(const Event& ev) {
    std::lock_guard<std::mutex> lock(logMutex);

    if (outFile.is_open()) {
        outFile << ev.getTimestamp() << "," // Now outputs "04/21/2026 18:24:09:452"
            << ev.getDeviceName() << ","
            << ev.getDeviceID() << ","
            << ev.getPanPos() << ","
            << ev.getTiltPos() << ","
            << ev.getSpeed() << "\n";
        outFile.flush();
    }
}

std::string Sweep_History::getName() const { return logName; }

