//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sweep_History.cpp
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#include "Sweep_History.h"

void Sweep_History::setName(int String) {
}

String Sweep_History::getName() {
}

void Sweep_History::addEvent(int List) {
}

List Sweep_History::getEventList() {
}

void Sweep_History::deleteHistory() {
}

