//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Sweep_History.h
//  @ Date : 3/25/2026
//  @ Author : 
//
//


#ifndef SWEEP_HISTORY_H
#define SWEEP_HISTORY_H

#include "Event.h"
#include <string>
#include <fstream>
#include <mutex>

class Sweep_History {
public:
    Sweep_History(std::string name);
    ~Sweep_History();

    void addEvent(const Event& ev);
    std::string getName() const;

private:
    std::string logName;
    std::ofstream outFile;
    std::mutex logMutex; // Prevents garbled text from concurrent threads
};

#endif
